CREATE TABLE IF NOT EXISTS survey_responses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TEXT DEFAULT CURRENT_TIMESTAMP,
  language TEXT,
  age TEXT,
  children TEXT,
  purchase_frequency TEXT,
  preference TEXT,
  intent INTEGER,
  psm_too_cheap INTEGER,
  psm_cheap INTEGER,
  psm_expensive INTEGER,
  psm_too_expensive INTEGER,
  local_importance INTEGER,
  premium_wtp TEXT,
  main_barrier TEXT,
  franui_visual INTEGER,
  franui_quality INTEGER,
  franui_health INTEGER,
  berrie_visual INTEGER,
  berrie_quality INTEGER,
  berrie_health INTEGER,
  client_ip TEXT
);
